import os
POSTGRES_USER=os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD=os.getenv('POSTGRES_PASSWORD')
POSTGRES_HOST=os.getenv('POSTGRES_HOST')
POSTGRES_PORT=int(os.getenv('POSTGRES_PORT'))
POSTGRES_DB= 'hidrografia'
SNAP_DISTANCE = 0.0001

EPSG_CODE=25830

